name: docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  mkdocs-link-check:

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: mkdocs-link-check (soft)
        uses: byrnereese/github-action-mkdocs-link-check@1.0
        continue-on-error: true
        with:
          recurse: 'yes'
          verbose-mode: 'yes'

  tasklist:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: MKDocs build
        run: mkdocs build --config-file mkdocs.yml --strict

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install requirements
        run: python3 -m pip install -r tasks/data_retrieval/requirements.txt

      - name: Fetch tasks data
        run: python3 -u tasks/data_retrieval/create_tasks_data.py

      - run: cat tasks/data_retrieval/tasks_data.json

      - name: Get package source code
        uses: actions/checkout@v4
        with:
          repository: fractal-analytics-platform/fractal-web
          ref: tasks-list-module

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install components dependencies
        run: |
          cd fractal-web/components
          npm install

      - name: Install tasks-list dependencies
        run: |
          cd fractal-web/tasks-list
          npm install

      - name: Move tasks.json file to fractal-web/tasks-list/src
        run: mv tasks/data_retrieval/tasks_data.json fractal-web/tasks-list/src/tasks.json

      - name: Build tasks-list
        run: |
          cd fractal-web/tasks-list
          npm run build

      - name: Move tasks-list built files in docs site
        run: mv fractal-web/tasks-list/build/ site/fractal-tasks

      - name: Deploy docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site