name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build-and-deploy:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4
        with:
          path: MAIN

      - uses: actions/checkout@v4
        with:
          repository: fractal-analytics-platform/fractal-web
          ref: tasks-list-module  # FIXME: replace with main (or latest tag?)
          path: WEB
          sparse-checkout: |
            components
            tasks-list
 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      # MKDocs build

      - name: Install dependencies
        run: python -m pip install -r MAIN/requirements.txt

      - name: MKDocs build
        run: mkdocs build --config-file MAIN/mkdocs.yml --strict --site-dir ./site

      - run: mv MAIN/site ./site
      - run: ls -lh ./site

      # Retrieve remote task-list data

      - name: Install requirements
        run: python3 -m pip install -r MAIN/tasks_data_retrieval/requirements.txt

      - name: Fetch tasks data
        run: python3 -u MAIN/tasks_data_retrieval/create_tasks_data.py

      - run: cat MAIN/tasks_data_retrieval/tasks.json

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: WEB/package-lock.json

      - name: Install components dependencies
        run: |
          cd WEB/components
          npm install

      - name: Install tasks-list dependencies
        run: |
          cd WEB/tasks-list
          npm install

      - name: Move tasks.json file to tasks-list/src
        run: mv MAIN/tasks_data_retrieval/tasks.json WEB/tasks-list/src/

      - name: Build tasks-list page
        run: |
          cd WEB/tasks-list
          npm run build

      - name: Move tasks-list built files in docs site
        run: mv WEB/tasks-list/build/ site/fractal-tasks

      - run: ls -lh site/*   # FIXME

      - name: Deploy docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # FIXME
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site