name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Re-run on a regular schedule
  schedule:
    - cron: "17 16 * * *"

  # Re-run on demand:
  workflow_dispatch:

permissions: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false

    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          path: MAIN
          persist-credentials: false

      - name: Set fractal-web reference
        run: |
          FRACTAL_WEB_REFERENCE=$(cat MAIN/fractal-web-reference.txt)
          echo "FRACTAL_WEB_REFERENCE=$FRACTAL_WEB_REFERENCE" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: fractal-analytics-platform/fractal-web
          ref: ${{ env.FRACTAL_WEB_REFERENCE }}
          path: WEB
          sparse-checkout: |
            components
            tasks-list
            templates-list
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
          cache: pip

      # MKDocs build

      - name: Install dependencies
        run: python -m pip install -r MAIN/requirements.txt

      - name: MKDocs build
        run: mkdocs build --config-file MAIN/mkdocs.yml --strict --site-dir ./site

      - run: mv MAIN/site ./site

      # Retrieve remote task-list data
      - run: python3 -m pip install -r MAIN/tasks_data_retrieval/requirements.txt
      - run: python3 -u MAIN/tasks_data_retrieval/create_tasks_data.py
      - run: cat MAIN/tasks_data_retrieval/tasks.json

      # Create templates-list data
      - run: python3 -u MAIN/templates_data_retrieval/create_templates_data.py
      - run: cat MAIN/templates_data_retrieval/templates.json
      - run: cat MAIN/templates_data_retrieval/template_id_map.json

      #  Fractal Web components
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: WEB/package-lock.json

      - name: Install main fractal-web dependencies
        run: |
          cd WEB
          npm install

      - name: Install components dependencies
        run: |
          cd WEB/components
          npm install

      # Tasks list

      - name: Install tasks-list dependencies
        run: |
          cd WEB/tasks-list
          npm install

      - name: Move tasks.json file to tasks-list/src
        run: mv MAIN/tasks_data_retrieval/tasks.json WEB/tasks-list/src/

      - name: Build tasks-list page
        run: |
          cd WEB/tasks-list
          npm run build

      - name: Move tasks-list built files in docs site
        run: mv WEB/tasks-list/build/ site/task-table

      # Templates list

      - name: Install templates-list dependencies
        run: |
          cd WEB/templates-list
          npm install

      - name: Move templates JSON files to templates-list/static
        run: |
          mv MAIN/templates_data_retrieval/{templates,template_id_map}.json WEB/templates-list/static/
          mv MAIN/templates_data_retrieval/raw/*.json WEB/templates-list/static/

      - name: Build templates-list page
        run: |
          cd WEB/templates-list
          npm run build

      - name: Move templates-list built files in docs site
        run: mv WEB/templates-list/build/ site/templates-table

      #  Timestamp

      - name: Set last-updated timestamp
        env:
          FRACTAL_WEB_REFERENCE: ${{ env.FRACTAL_WEB_REFERENCE }}
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M %Z")
          echo "$CURRENT_DATE"
          sed -i'.bak1' "s/LASTUPDATEDPLACEHOLDER/$CURRENT_DATE/" site/fractal_tasks/index.html
          sed -i'.bak2' "s/FRACTALWEBREFERENCEPLACEHOLDER/${FRACTAL_WEB_REFERENCE}/" site/fractal_tasks/index.html
          rm site/fractal_tasks/index.html.bak1 site/fractal_tasks/index.html.bak2
          sed -i'.bak1' "s/LASTUPDATEDPLACEHOLDER/$CURRENT_DATE/" site/fractal_templates/index.html
          sed -i'.bak2' "s/FRACTALWEBREFERENCEPLACEHOLDER/${FRACTAL_WEB_REFERENCE}/" site/fractal_templates/index.html
          rm site/fractal_templates/index.html.bak1 site/fractal_templates/index.html.bak2

      - run: ls -lh site/*

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: "site"

  deploy:
    name: Deploy
    if: ${{ ( ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) && ( github.event.ref == 'refs/heads/main' ) ) || ( github.event_name == 'schedule' )}}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      # https://github.com/actions/deploy-pages?tab=readme-ov-file
      # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers#adding-permissions-settings
      pages: write  # To create pages deployments when calling the GitHub API
      id-token: write # To request the OIDC JWT token
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
        id: deployment
