name: Build and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build-and-deploy:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4
        with:
          path: MAIN

      - uses: actions/checkout@v4
        with:
          repository: fractal-analytics-platform/fractal-web
          ref: tasks-list-module  # FIXME
          path: fractal-web
          # sparse-checkout: |  # FIXME
          #   components
          #   tasks-list
 

      - run: pwd  # FIXME
      - run: ls -lh * */* # FIXME

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      # MKDocs build

      # - name: Install dependencies
      #   run: python -m pip install -r MAIN/requirements.txt

      # - name: MKDocs build
        # run: mkdocs build --config-file MAIN/mkdocs.yml --strict

      # Retrieve remote task-list data

      - name: Install requirements
        run: python3 -m pip install -r MAIN/tasks/data_retrieval/requirements.txt

      - name: Fetch tasks data
        run: python3 -u MAIN/tasks/data_retrieval/create_tasks_data.py

      - run: cat MAIN/tasks/data_retrieval/tasks_data.json

      - run: pwd  # FIXME
      - run: ls -lh * */* # FIXME

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: fractal-web/package-lock.json

      - run: pwd  # FIXME
      - run: ls -lh * */* # FIXME

      - name: Install components dependencies
        run: |
          cd fractal-web/components
          npm install

      - name: Install tasks-list dependencies
        run: |
          cd fractal-web/tasks-list
          npm install

      - run: pwd  # FIXME
      - run: ls -lh * */* # FIXME

      - name: Move tasks.json file to tasks-list/src
        run: mv MAIN/tasks/data_retrieval/tasks_data.json fractal-web/tasks-list/src/tasks.json

      - name: Build tasks-list page
        run: |
          cd fractal-web/tasks-list
          npm run build

      - name: Move tasks-list built files in docs site
        run: mv fractal-web/tasks-list/build/ MAIN/site/fractal-tasks

      - name: Deploy docs
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site