name: Task-list page

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


jobs:
  retrieve-tasks-data:
    runs-on: ubuntu-latest
  
    steps:

      # Fetch data

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install requirements
        run: python3 -m pip install -r tasks/data_retrieval/requirements.txt

      - name: Fetch tasks data
        run: python3 -u tasks/data_retrieval/create_tasks_data.py

      - run: cat tasks/data_retrieval/tasks_data.json

      - run: cp tasks/data_retrieval/tasks_data.json tasks.json

      # Build tasks-list page

      - name: Get package source code
        uses: actions/checkout@v4
        with:
          repository: fractal-analytics-platform/fractal-web

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install components dependencies
        run: |
          cd fractal-web/components
          npm install

      - name: Install task-list dependencies
        run: |
          cd fractal-web/task-list
          npm install

      - name: Move tasks.json file

      - name: Build task-list
        run: |
          cd fractal-web/task-list
          npm run build

      - name: Move sandbox built files in docs site
        run: mv fractal-web/task-list/build/ site/fractal-tasks
